#ifndef __INSTRUCTIONS_HPP__
#define __INSTRUCTIONS_HPP__

#include "z80/cpu.h"

#include <cstdint>
#include <array>


namespace genesis::z80
{

enum operation_type : std::uint8_t
{
	unknown,

	/* 8-Bit Arithmetic Group */
	add,
	adc,
	sub,
	sbc,
	and_8,
	or_8,
	xor_8,
	cp,
	inc_reg,
	inc_at,
	dec_reg,
	dec_at,

	/* 16-Bit Arithmetic Group */
	add_16,
	adc_hl,
	sbc_hl,
	inc_reg_16,
	dec_reg_16,

	/* 8/16-Bit Load Group */
	ld_reg,
	ld_at,
	ld_ir,
	ld_16_reg,
	ld_16_reg_from,
	ld_16_at,
	push,
	pop,

	/* Call and Return Group */
	call,
	call_cc,
	rst,
	ret,
	reti,
	retn,
	ret_cc,

	/* Jump Group */
	jp,
	jp_cc,
	jr_z,
	jr_nz,
	jr_c,
	jr_nc,
	jr,
	djnz,

	/* Input and Output Group */
	in,
	in_reg,
	ini,
	inir,
	ind,
	indr,
	out,
	out_reg,
	outi,
	otir,
	outd,
	otdr,

	/* Exchange, Block Transfer, and Search Group */
	ex_de_hl,
	ex_af_afs,
	exx,
	ex_16_at,
	ldi,
	ldir,
	cpd,
	cpdr,
	cpi,
	cpir,
	ldd,
	lddr,

	/* Rotate and Shift Group */
	rlca,
	rrca,
	rla,
	rra,
	rld,
	rrd,
	rlc,
	rlc_at,
	rrc,
	rrc_at,
	rl,
	rl_at,
	rr,
	rr_at,
	sla,
	sla_at,
	sra,
	sra_at,
	srl,
	srl_at,
	sll,
	sll_at,

	/* Bit Set, Reset, and Test Group */
	tst_bit,
	tst_bit_at,
	set_bit,
	set_bit_at,
	res_bit,
	res_bit_at,
	bit_group,

	/* General-Purpose Arithmetic */
	daa,
	cpl,
	neg,
	ccf,
	scf,

	/* CPU Control Groups */
	di,
	ei,
	nop,
	halt,
	im0,
	im1,
	im2,
};

enum addressing_mode : std::uint8_t
{
	none,

	implied,

	// register
	register_a,
	register_b,
	register_c,
	register_d,
	register_e,
	register_h,
	register_l,

	register_i,
	register_r,

	// register pair
	register_af,
	register_bc,
	register_de,
	register_hl,
	register_sp,
	register_ix,
	register_iy,

	register_ixh,
	register_ixl,
	register_iyh,
	register_iyl,

	// immediate
	immediate,
	immediate_ext,

	// indirect
	indirect_hl,
	indirect_bc,
	indirect_de,
	indirect_sp,

	// indexed
	indexed_ix,
	indexed_iy,

	// bit
	bit,
	immediate_bit,
	
};

class instruction
{
public:
	z80::operation_type op_type;
	std::array<z80::opcode, 2> opcodes = {0x0, 0x0};

	addressing_mode source;
	addressing_mode destination;
};

const instruction instructions[] = {
	{ operation_type::add, {0x87}, addressing_mode::register_a, addressing_mode::implied },
	{ operation_type::add, {0x80}, addressing_mode::register_b, addressing_mode::implied },
	{ operation_type::add, {0x81}, addressing_mode::register_c, addressing_mode::implied },
	{ operation_type::add, {0x82}, addressing_mode::register_d, addressing_mode::implied },
	{ operation_type::add, {0x83}, addressing_mode::register_e, addressing_mode::implied },
	{ operation_type::add, {0x84}, addressing_mode::register_h, addressing_mode::implied },
	{ operation_type::add, {0x85}, addressing_mode::register_l, addressing_mode::implied },
	{ operation_type::add, {0xC6}, addressing_mode::immediate, addressing_mode::implied },
	{ operation_type::add, {0x86}, addressing_mode::indirect_hl, addressing_mode::implied },
	{ operation_type::add, {0xDD, 0x84}, addressing_mode::register_ixh, addressing_mode::implied },
	{ operation_type::add, {0xDD, 0x85}, addressing_mode::register_ixl, addressing_mode::implied },
	{ operation_type::add, {0xDD, 0x86}, addressing_mode::indexed_ix, addressing_mode::implied },
	{ operation_type::add, {0xFD, 0x84}, addressing_mode::register_iyh, addressing_mode::implied },
	{ operation_type::add, {0xFD, 0x85}, addressing_mode::register_iyl, addressing_mode::implied },
	{ operation_type::add, {0xFD, 0x86}, addressing_mode::indexed_iy, addressing_mode::implied },
	{ operation_type::adc, {0x8F}, addressing_mode::register_a, addressing_mode::implied },
	{ operation_type::adc, {0x88}, addressing_mode::register_b, addressing_mode::implied },
	{ operation_type::adc, {0x89}, addressing_mode::register_c, addressing_mode::implied },
	{ operation_type::adc, {0x8A}, addressing_mode::register_d, addressing_mode::implied },
	{ operation_type::adc, {0x8B}, addressing_mode::register_e, addressing_mode::implied },
	{ operation_type::adc, {0x8C}, addressing_mode::register_h, addressing_mode::implied },
	{ operation_type::adc, {0x8D}, addressing_mode::register_l, addressing_mode::implied },
	{ operation_type::adc, {0xCE}, addressing_mode::immediate, addressing_mode::implied },
	{ operation_type::adc, {0x8E}, addressing_mode::indirect_hl, addressing_mode::implied },
	{ operation_type::adc, {0xDD, 0x8C}, addressing_mode::register_ixh, addressing_mode::implied },
	{ operation_type::adc, {0xDD, 0x8D}, addressing_mode::register_ixl, addressing_mode::implied },
	{ operation_type::adc, {0xDD, 0x8E}, addressing_mode::indexed_ix, addressing_mode::implied },
	{ operation_type::adc, {0xFD, 0x8C}, addressing_mode::register_iyh, addressing_mode::implied },
	{ operation_type::adc, {0xFD, 0x8D}, addressing_mode::register_iyl, addressing_mode::implied },
	{ operation_type::adc, {0xFD, 0x8E}, addressing_mode::indexed_iy, addressing_mode::implied },
	{ operation_type::sub, {0x97}, addressing_mode::register_a, addressing_mode::implied },
	{ operation_type::sub, {0x90}, addressing_mode::register_b, addressing_mode::implied },
	{ operation_type::sub, {0x91}, addressing_mode::register_c, addressing_mode::implied },
	{ operation_type::sub, {0x92}, addressing_mode::register_d, addressing_mode::implied },
	{ operation_type::sub, {0x93}, addressing_mode::register_e, addressing_mode::implied },
	{ operation_type::sub, {0x94}, addressing_mode::register_h, addressing_mode::implied },
	{ operation_type::sub, {0x95}, addressing_mode::register_l, addressing_mode::implied },
	{ operation_type::sub, {0xD6}, addressing_mode::immediate, addressing_mode::implied },
	{ operation_type::sub, {0x96}, addressing_mode::indirect_hl, addressing_mode::implied },
	{ operation_type::sub, {0xDD, 0x94}, addressing_mode::register_ixh, addressing_mode::implied },
	{ operation_type::sub, {0xDD, 0x95}, addressing_mode::register_ixl, addressing_mode::implied },
	{ operation_type::sub, {0xDD, 0x96}, addressing_mode::indexed_ix, addressing_mode::implied },
	{ operation_type::sub, {0xFD, 0x94}, addressing_mode::register_iyh, addressing_mode::implied },
	{ operation_type::sub, {0xFD, 0x95}, addressing_mode::register_iyl, addressing_mode::implied },
	{ operation_type::sub, {0xFD, 0x96}, addressing_mode::indexed_iy, addressing_mode::implied },
	{ operation_type::sbc, {0x9F}, addressing_mode::register_a, addressing_mode::implied },
	{ operation_type::sbc, {0x98}, addressing_mode::register_b, addressing_mode::implied },
	{ operation_type::sbc, {0x99}, addressing_mode::register_c, addressing_mode::implied },
	{ operation_type::sbc, {0x9A}, addressing_mode::register_d, addressing_mode::implied },
	{ operation_type::sbc, {0x9B}, addressing_mode::register_e, addressing_mode::implied },
	{ operation_type::sbc, {0x9C}, addressing_mode::register_h, addressing_mode::implied },
	{ operation_type::sbc, {0x9D}, addressing_mode::register_l, addressing_mode::implied },
	{ operation_type::sbc, {0xDE}, addressing_mode::immediate, addressing_mode::implied },
	{ operation_type::sbc, {0x9E}, addressing_mode::indirect_hl, addressing_mode::implied },
	{ operation_type::sbc, {0xDD, 0x9C}, addressing_mode::register_ixh, addressing_mode::implied },
	{ operation_type::sbc, {0xDD, 0x9D}, addressing_mode::register_ixl, addressing_mode::implied },
	{ operation_type::sbc, {0xDD, 0x9E}, addressing_mode::indexed_ix, addressing_mode::implied },
	{ operation_type::sbc, {0xFD, 0x9C}, addressing_mode::register_iyh, addressing_mode::implied },
	{ operation_type::sbc, {0xFD, 0x9D}, addressing_mode::register_iyl, addressing_mode::implied },
	{ operation_type::sbc, {0xFD, 0x9E}, addressing_mode::indexed_iy, addressing_mode::implied },
	{ operation_type::and_8, {0xA7}, addressing_mode::register_a, addressing_mode::implied },
	{ operation_type::and_8, {0xA0}, addressing_mode::register_b, addressing_mode::implied },
	{ operation_type::and_8, {0xA1}, addressing_mode::register_c, addressing_mode::implied },
	{ operation_type::and_8, {0xA2}, addressing_mode::register_d, addressing_mode::implied },
	{ operation_type::and_8, {0xA3}, addressing_mode::register_e, addressing_mode::implied },
	{ operation_type::and_8, {0xA4}, addressing_mode::register_h, addressing_mode::implied },
	{ operation_type::and_8, {0xA5}, addressing_mode::register_l, addressing_mode::implied },
	{ operation_type::and_8, {0xE6}, addressing_mode::immediate, addressing_mode::implied },
	{ operation_type::and_8, {0xA6}, addressing_mode::indirect_hl, addressing_mode::implied },
	{ operation_type::and_8, {0xDD, 0xA4}, addressing_mode::register_ixh, addressing_mode::implied },
	{ operation_type::and_8, {0xDD, 0xA5}, addressing_mode::register_ixl, addressing_mode::implied },
	{ operation_type::and_8, {0xDD, 0xA6}, addressing_mode::indexed_ix, addressing_mode::implied },
	{ operation_type::and_8, {0xFD, 0xA4}, addressing_mode::register_iyh, addressing_mode::implied },
	{ operation_type::and_8, {0xFD, 0xA5}, addressing_mode::register_iyl, addressing_mode::implied },
	{ operation_type::and_8, {0xFD, 0xA6}, addressing_mode::indexed_iy, addressing_mode::implied },
	{ operation_type::or_8, {0xB7}, addressing_mode::register_a, addressing_mode::implied },
	{ operation_type::or_8, {0xB0}, addressing_mode::register_b, addressing_mode::implied },
	{ operation_type::or_8, {0xB1}, addressing_mode::register_c, addressing_mode::implied },
	{ operation_type::or_8, {0xB2}, addressing_mode::register_d, addressing_mode::implied },
	{ operation_type::or_8, {0xB3}, addressing_mode::register_e, addressing_mode::implied },
	{ operation_type::or_8, {0xB4}, addressing_mode::register_h, addressing_mode::implied },
	{ operation_type::or_8, {0xB5}, addressing_mode::register_l, addressing_mode::implied },
	{ operation_type::or_8, {0xF6}, addressing_mode::immediate, addressing_mode::implied },
	{ operation_type::or_8, {0xB6}, addressing_mode::indirect_hl, addressing_mode::implied },
	{ operation_type::or_8, {0xDD, 0xB4}, addressing_mode::register_ixh, addressing_mode::implied },
	{ operation_type::or_8, {0xDD, 0xB5}, addressing_mode::register_ixl, addressing_mode::implied },
	{ operation_type::or_8, {0xDD, 0xB6}, addressing_mode::indexed_ix, addressing_mode::implied },
	{ operation_type::or_8, {0xFD, 0xB4}, addressing_mode::register_iyh, addressing_mode::implied },
	{ operation_type::or_8, {0xFD, 0xB5}, addressing_mode::register_iyl, addressing_mode::implied },
	{ operation_type::or_8, {0xFD, 0xB6}, addressing_mode::indexed_iy, addressing_mode::implied },
	{ operation_type::xor_8, {0xAF}, addressing_mode::register_a, addressing_mode::implied },
	{ operation_type::xor_8, {0xA8}, addressing_mode::register_b, addressing_mode::implied },
	{ operation_type::xor_8, {0xA9}, addressing_mode::register_c, addressing_mode::implied },
	{ operation_type::xor_8, {0xAA}, addressing_mode::register_d, addressing_mode::implied },
	{ operation_type::xor_8, {0xAB}, addressing_mode::register_e, addressing_mode::implied },
	{ operation_type::xor_8, {0xAC}, addressing_mode::register_h, addressing_mode::implied },
	{ operation_type::xor_8, {0xAD}, addressing_mode::register_l, addressing_mode::implied },
	{ operation_type::xor_8, {0xEE}, addressing_mode::immediate, addressing_mode::implied },
	{ operation_type::xor_8, {0xAE}, addressing_mode::indirect_hl, addressing_mode::implied },
	{ operation_type::xor_8, {0xDD, 0xAC}, addressing_mode::register_ixh, addressing_mode::implied },
	{ operation_type::xor_8, {0xDD, 0xAD}, addressing_mode::register_ixl, addressing_mode::implied },
	{ operation_type::xor_8, {0xDD, 0xAE}, addressing_mode::indexed_ix, addressing_mode::implied },
	{ operation_type::xor_8, {0xFD, 0xAC}, addressing_mode::register_iyh, addressing_mode::implied },
	{ operation_type::xor_8, {0xFD, 0xAD}, addressing_mode::register_iyl, addressing_mode::implied },
	{ operation_type::xor_8, {0xFD, 0xAE}, addressing_mode::indexed_iy, addressing_mode::implied },
	{ operation_type::cp, {0xBF}, addressing_mode::register_a, addressing_mode::implied },
	{ operation_type::cp, {0xB8}, addressing_mode::register_b, addressing_mode::implied },
	{ operation_type::cp, {0xB9}, addressing_mode::register_c, addressing_mode::implied },
	{ operation_type::cp, {0xBA}, addressing_mode::register_d, addressing_mode::implied },
	{ operation_type::cp, {0xBB}, addressing_mode::register_e, addressing_mode::implied },
	{ operation_type::cp, {0xBC}, addressing_mode::register_h, addressing_mode::implied },
	{ operation_type::cp, {0xBD}, addressing_mode::register_l, addressing_mode::implied },
	{ operation_type::cp, {0xFE}, addressing_mode::immediate, addressing_mode::implied },
	{ operation_type::cp, {0xBE}, addressing_mode::indirect_hl, addressing_mode::implied },
	{ operation_type::cp, {0xDD, 0xBC}, addressing_mode::register_ixh, addressing_mode::implied },
	{ operation_type::cp, {0xDD, 0xBD}, addressing_mode::register_ixl, addressing_mode::implied },
	{ operation_type::cp, {0xDD, 0xBE}, addressing_mode::indexed_ix, addressing_mode::implied },
	{ operation_type::cp, {0xFD, 0xBC}, addressing_mode::register_iyh, addressing_mode::implied },
	{ operation_type::cp, {0xFD, 0xBD}, addressing_mode::register_iyl, addressing_mode::implied },
	{ operation_type::cp, {0xFD, 0xBE}, addressing_mode::indexed_iy, addressing_mode::implied },
	{ operation_type::inc_reg, {0x3C}, addressing_mode::register_a, addressing_mode::implied },
	{ operation_type::inc_reg, {0x04}, addressing_mode::register_b, addressing_mode::implied },
	{ operation_type::inc_reg, {0x0C}, addressing_mode::register_c, addressing_mode::implied },
	{ operation_type::inc_reg, {0x14}, addressing_mode::register_d, addressing_mode::implied },
	{ operation_type::inc_reg, {0x1C}, addressing_mode::register_e, addressing_mode::implied },
	{ operation_type::inc_reg, {0x24}, addressing_mode::register_h, addressing_mode::implied },
	{ operation_type::inc_reg, {0x2C}, addressing_mode::register_l, addressing_mode::implied },
	{ operation_type::inc_reg, {0xDD, 0x24}, addressing_mode::register_ixh, addressing_mode::register_ixh },
	{ operation_type::inc_reg, {0xDD, 0x2C}, addressing_mode::register_ixl, addressing_mode::register_ixl },
	{ operation_type::inc_reg, {0xFD, 0x24}, addressing_mode::register_iyh, addressing_mode::register_iyh },
	{ operation_type::inc_reg, {0xFD, 0x2C}, addressing_mode::register_iyl, addressing_mode::register_iyl },
	{ operation_type::inc_at, {0x34}, addressing_mode::indirect_hl, addressing_mode::indirect_hl },
	{ operation_type::inc_at, {0xDD, 0x34}, addressing_mode::indexed_ix, addressing_mode::indexed_ix },
	{ operation_type::inc_at, {0xFD, 0x34}, addressing_mode::indexed_iy, addressing_mode::indexed_iy },
	{ operation_type::dec_reg, {0x3D}, addressing_mode::register_a, addressing_mode::implied },
	{ operation_type::dec_reg, {0x05}, addressing_mode::register_b, addressing_mode::implied },
	{ operation_type::dec_reg, {0x0D}, addressing_mode::register_c, addressing_mode::implied },
	{ operation_type::dec_reg, {0x15}, addressing_mode::register_d, addressing_mode::implied },
	{ operation_type::dec_reg, {0x1D}, addressing_mode::register_e, addressing_mode::implied },
	{ operation_type::dec_reg, {0x25}, addressing_mode::register_h, addressing_mode::implied },
	{ operation_type::dec_reg, {0x2D}, addressing_mode::register_l, addressing_mode::implied },
	{ operation_type::dec_reg, {0xDD, 0x25}, addressing_mode::register_ixh, addressing_mode::register_ixh },
	{ operation_type::dec_reg, {0xDD, 0x2D}, addressing_mode::register_ixl, addressing_mode::register_ixl },
	{ operation_type::dec_reg, {0xFD, 0x25}, addressing_mode::register_iyh, addressing_mode::register_iyh },
	{ operation_type::dec_reg, {0xFD, 0x2D}, addressing_mode::register_iyl, addressing_mode::register_iyl },
	{ operation_type::dec_at, {0x35}, addressing_mode::indirect_hl, addressing_mode::indirect_hl },
	{ operation_type::dec_at, {0xDD, 0x35}, addressing_mode::indexed_ix, addressing_mode::indexed_ix },
	{ operation_type::dec_at, {0xFD, 0x35}, addressing_mode::indexed_iy, addressing_mode::indexed_iy },
	{ operation_type::add_16, {0x09}, addressing_mode::register_bc, addressing_mode::register_hl },
	{ operation_type::add_16, {0x19}, addressing_mode::register_de, addressing_mode::register_hl },
	{ operation_type::add_16, {0x29}, addressing_mode::register_hl, addressing_mode::register_hl },
	{ operation_type::add_16, {0x39}, addressing_mode::register_sp, addressing_mode::register_hl },
	{ operation_type::add_16, {0xDD, 0x09}, addressing_mode::register_bc, addressing_mode::register_ix },
	{ operation_type::add_16, {0xDD, 0x19}, addressing_mode::register_de, addressing_mode::register_ix },
	{ operation_type::add_16, {0xDD, 0x39}, addressing_mode::register_sp, addressing_mode::register_ix },
	{ operation_type::add_16, {0xDD, 0x29}, addressing_mode::register_ix, addressing_mode::register_ix },
	{ operation_type::add_16, {0xFD, 0x09}, addressing_mode::register_bc, addressing_mode::register_iy },
	{ operation_type::add_16, {0xFD, 0x19}, addressing_mode::register_de, addressing_mode::register_iy },
	{ operation_type::add_16, {0xFD, 0x39}, addressing_mode::register_sp, addressing_mode::register_iy },
	{ operation_type::add_16, {0xFD, 0x29}, addressing_mode::register_iy, addressing_mode::register_iy },
	{ operation_type::adc_hl, {0xED, 0x4A}, addressing_mode::register_bc, addressing_mode::implied },
	{ operation_type::adc_hl, {0xED, 0x5A}, addressing_mode::register_de, addressing_mode::implied },
	{ operation_type::adc_hl, {0xED, 0x6A}, addressing_mode::register_hl, addressing_mode::implied },
	{ operation_type::adc_hl, {0xED, 0x7A}, addressing_mode::register_sp, addressing_mode::implied },
	{ operation_type::sbc_hl, {0xED, 0x42}, addressing_mode::register_bc, addressing_mode::implied },
	{ operation_type::sbc_hl, {0xED, 0x52}, addressing_mode::register_de, addressing_mode::implied },
	{ operation_type::sbc_hl, {0xED, 0x62}, addressing_mode::register_hl, addressing_mode::implied },
	{ operation_type::sbc_hl, {0xED, 0x72}, addressing_mode::register_sp, addressing_mode::implied },
	{ operation_type::inc_reg_16, {0x03}, addressing_mode::register_bc, addressing_mode::register_bc },
	{ operation_type::inc_reg_16, {0x13}, addressing_mode::register_de, addressing_mode::register_de },
	{ operation_type::inc_reg_16, {0x23}, addressing_mode::register_hl, addressing_mode::register_hl },
	{ operation_type::inc_reg_16, {0x33}, addressing_mode::register_sp, addressing_mode::register_sp },
	{ operation_type::inc_reg_16, {0xDD, 0x23}, addressing_mode::register_ix, addressing_mode::register_ix },
	{ operation_type::inc_reg_16, {0xFD, 0x23}, addressing_mode::register_iy, addressing_mode::register_iy },
	{ operation_type::dec_reg_16, {0x0B}, addressing_mode::register_bc, addressing_mode::register_bc },
	{ operation_type::dec_reg_16, {0x1B}, addressing_mode::register_de, addressing_mode::register_de },
	{ operation_type::dec_reg_16, {0x2B}, addressing_mode::register_hl, addressing_mode::register_hl },
	{ operation_type::dec_reg_16, {0x3B}, addressing_mode::register_sp, addressing_mode::register_sp },
	{ operation_type::dec_reg_16, {0xDD, 0x2B}, addressing_mode::register_ix, addressing_mode::register_ix },
	{ operation_type::dec_reg_16, {0xFD, 0x2B}, addressing_mode::register_iy, addressing_mode::register_iy },
	{ operation_type::ld_reg, {0x7F}, addressing_mode::register_a, addressing_mode::register_a },
	{ operation_type::ld_reg, {0x47}, addressing_mode::register_a, addressing_mode::register_b },
	{ operation_type::ld_reg, {0x4F}, addressing_mode::register_a, addressing_mode::register_c },
	{ operation_type::ld_reg, {0x57}, addressing_mode::register_a, addressing_mode::register_d },
	{ operation_type::ld_reg, {0x5F}, addressing_mode::register_a, addressing_mode::register_e },
	{ operation_type::ld_reg, {0x67}, addressing_mode::register_a, addressing_mode::register_h },
	{ operation_type::ld_reg, {0x6F}, addressing_mode::register_a, addressing_mode::register_l },
	{ operation_type::ld_reg, {0x78}, addressing_mode::register_b, addressing_mode::register_a },
	{ operation_type::ld_reg, {0x40}, addressing_mode::register_b, addressing_mode::register_b },
	{ operation_type::ld_reg, {0x48}, addressing_mode::register_b, addressing_mode::register_c },
	{ operation_type::ld_reg, {0x50}, addressing_mode::register_b, addressing_mode::register_d },
	{ operation_type::ld_reg, {0x58}, addressing_mode::register_b, addressing_mode::register_e },
	{ operation_type::ld_reg, {0x60}, addressing_mode::register_b, addressing_mode::register_h },
	{ operation_type::ld_reg, {0x68}, addressing_mode::register_b, addressing_mode::register_l },
	{ operation_type::ld_reg, {0x79}, addressing_mode::register_c, addressing_mode::register_a },
	{ operation_type::ld_reg, {0x41}, addressing_mode::register_c, addressing_mode::register_b },
	{ operation_type::ld_reg, {0x49}, addressing_mode::register_c, addressing_mode::register_c },
	{ operation_type::ld_reg, {0x51}, addressing_mode::register_c, addressing_mode::register_d },
	{ operation_type::ld_reg, {0x59}, addressing_mode::register_c, addressing_mode::register_e },
	{ operation_type::ld_reg, {0x61}, addressing_mode::register_c, addressing_mode::register_h },
	{ operation_type::ld_reg, {0x69}, addressing_mode::register_c, addressing_mode::register_l },
	{ operation_type::ld_reg, {0x7A}, addressing_mode::register_d, addressing_mode::register_a },
	{ operation_type::ld_reg, {0x42}, addressing_mode::register_d, addressing_mode::register_b },
	{ operation_type::ld_reg, {0x4A}, addressing_mode::register_d, addressing_mode::register_c },
	{ operation_type::ld_reg, {0x52}, addressing_mode::register_d, addressing_mode::register_d },
	{ operation_type::ld_reg, {0x5A}, addressing_mode::register_d, addressing_mode::register_e },
	{ operation_type::ld_reg, {0x62}, addressing_mode::register_d, addressing_mode::register_h },
	{ operation_type::ld_reg, {0x6A}, addressing_mode::register_d, addressing_mode::register_l },
	{ operation_type::ld_reg, {0x7B}, addressing_mode::register_e, addressing_mode::register_a },
	{ operation_type::ld_reg, {0x43}, addressing_mode::register_e, addressing_mode::register_b },
	{ operation_type::ld_reg, {0x4B}, addressing_mode::register_e, addressing_mode::register_c },
	{ operation_type::ld_reg, {0x53}, addressing_mode::register_e, addressing_mode::register_d },
	{ operation_type::ld_reg, {0x5B}, addressing_mode::register_e, addressing_mode::register_e },
	{ operation_type::ld_reg, {0x63}, addressing_mode::register_e, addressing_mode::register_h },
	{ operation_type::ld_reg, {0x6B}, addressing_mode::register_e, addressing_mode::register_l },
	{ operation_type::ld_reg, {0x7C}, addressing_mode::register_h, addressing_mode::register_a },
	{ operation_type::ld_reg, {0x44}, addressing_mode::register_h, addressing_mode::register_b },
	{ operation_type::ld_reg, {0x4C}, addressing_mode::register_h, addressing_mode::register_c },
	{ operation_type::ld_reg, {0x54}, addressing_mode::register_h, addressing_mode::register_d },
	{ operation_type::ld_reg, {0x5C}, addressing_mode::register_h, addressing_mode::register_e },
	{ operation_type::ld_reg, {0x64}, addressing_mode::register_h, addressing_mode::register_h },
	{ operation_type::ld_reg, {0x6C}, addressing_mode::register_h, addressing_mode::register_l },
	{ operation_type::ld_reg, {0x7D}, addressing_mode::register_l, addressing_mode::register_a },
	{ operation_type::ld_reg, {0x45}, addressing_mode::register_l, addressing_mode::register_b },
	{ operation_type::ld_reg, {0x4D}, addressing_mode::register_l, addressing_mode::register_c },
	{ operation_type::ld_reg, {0x55}, addressing_mode::register_l, addressing_mode::register_d },
	{ operation_type::ld_reg, {0x5D}, addressing_mode::register_l, addressing_mode::register_e },
	{ operation_type::ld_reg, {0x65}, addressing_mode::register_l, addressing_mode::register_h },
	{ operation_type::ld_reg, {0x6D}, addressing_mode::register_l, addressing_mode::register_l },
	{ operation_type::ld_reg, {0x3E}, addressing_mode::immediate, addressing_mode::register_a },
	{ operation_type::ld_reg, {0x06}, addressing_mode::immediate, addressing_mode::register_b },
	{ operation_type::ld_reg, {0x0E}, addressing_mode::immediate, addressing_mode::register_c },
	{ operation_type::ld_reg, {0x16}, addressing_mode::immediate, addressing_mode::register_d },
	{ operation_type::ld_reg, {0x1E}, addressing_mode::immediate, addressing_mode::register_e },
	{ operation_type::ld_reg, {0x26}, addressing_mode::immediate, addressing_mode::register_h },
	{ operation_type::ld_reg, {0x2E}, addressing_mode::immediate, addressing_mode::register_l },
	{ operation_type::ld_reg, {0x3A}, addressing_mode::immediate_ext, addressing_mode::register_a },
	{ operation_type::ld_reg, {0x7E}, addressing_mode::indirect_hl, addressing_mode::register_a },
	{ operation_type::ld_reg, {0x46}, addressing_mode::indirect_hl, addressing_mode::register_b },
	{ operation_type::ld_reg, {0x4E}, addressing_mode::indirect_hl, addressing_mode::register_c },
	{ operation_type::ld_reg, {0x56}, addressing_mode::indirect_hl, addressing_mode::register_d },
	{ operation_type::ld_reg, {0x5E}, addressing_mode::indirect_hl, addressing_mode::register_e },
	{ operation_type::ld_reg, {0x66}, addressing_mode::indirect_hl, addressing_mode::register_h },
	{ operation_type::ld_reg, {0x6E}, addressing_mode::indirect_hl, addressing_mode::register_l },
	{ operation_type::ld_reg, {0x0A}, addressing_mode::indirect_bc, addressing_mode::register_a },
	{ operation_type::ld_reg, {0x1A}, addressing_mode::indirect_de, addressing_mode::register_a },
	{ operation_type::ld_reg, {0xDD, 0x7F}, addressing_mode::register_a, addressing_mode::register_a },
	{ operation_type::ld_reg, {0xDD, 0x47}, addressing_mode::register_a, addressing_mode::register_b },
	{ operation_type::ld_reg, {0xDD, 0x4F}, addressing_mode::register_a, addressing_mode::register_c },
	{ operation_type::ld_reg, {0xDD, 0x57}, addressing_mode::register_a, addressing_mode::register_d },
	{ operation_type::ld_reg, {0xDD, 0x5F}, addressing_mode::register_a, addressing_mode::register_e },
	{ operation_type::ld_reg, {0xDD, 0x67}, addressing_mode::register_a, addressing_mode::register_ixh },
	{ operation_type::ld_reg, {0xDD, 0x6F}, addressing_mode::register_a, addressing_mode::register_ixl },
	{ operation_type::ld_reg, {0xDD, 0x78}, addressing_mode::register_b, addressing_mode::register_a },
	{ operation_type::ld_reg, {0xDD, 0x40}, addressing_mode::register_b, addressing_mode::register_b },
	{ operation_type::ld_reg, {0xDD, 0x48}, addressing_mode::register_b, addressing_mode::register_c },
	{ operation_type::ld_reg, {0xDD, 0x50}, addressing_mode::register_b, addressing_mode::register_d },
	{ operation_type::ld_reg, {0xDD, 0x58}, addressing_mode::register_b, addressing_mode::register_e },
	{ operation_type::ld_reg, {0xDD, 0x60}, addressing_mode::register_b, addressing_mode::register_ixh },
	{ operation_type::ld_reg, {0xDD, 0x68}, addressing_mode::register_b, addressing_mode::register_ixl },
	{ operation_type::ld_reg, {0xDD, 0x79}, addressing_mode::register_c, addressing_mode::register_a },
	{ operation_type::ld_reg, {0xDD, 0x41}, addressing_mode::register_c, addressing_mode::register_b },
	{ operation_type::ld_reg, {0xDD, 0x49}, addressing_mode::register_c, addressing_mode::register_c },
	{ operation_type::ld_reg, {0xDD, 0x51}, addressing_mode::register_c, addressing_mode::register_d },
	{ operation_type::ld_reg, {0xDD, 0x59}, addressing_mode::register_c, addressing_mode::register_e },
	{ operation_type::ld_reg, {0xDD, 0x61}, addressing_mode::register_c, addressing_mode::register_ixh },
	{ operation_type::ld_reg, {0xDD, 0x69}, addressing_mode::register_c, addressing_mode::register_ixl },
	{ operation_type::ld_reg, {0xDD, 0x7A}, addressing_mode::register_d, addressing_mode::register_a },
	{ operation_type::ld_reg, {0xDD, 0x42}, addressing_mode::register_d, addressing_mode::register_b },
	{ operation_type::ld_reg, {0xDD, 0x4A}, addressing_mode::register_d, addressing_mode::register_c },
	{ operation_type::ld_reg, {0xDD, 0x52}, addressing_mode::register_d, addressing_mode::register_d },
	{ operation_type::ld_reg, {0xDD, 0x5A}, addressing_mode::register_d, addressing_mode::register_e },
	{ operation_type::ld_reg, {0xDD, 0x62}, addressing_mode::register_d, addressing_mode::register_ixh },
	{ operation_type::ld_reg, {0xDD, 0x6A}, addressing_mode::register_d, addressing_mode::register_ixl },
	{ operation_type::ld_reg, {0xDD, 0x7B}, addressing_mode::register_e, addressing_mode::register_a },
	{ operation_type::ld_reg, {0xDD, 0x43}, addressing_mode::register_e, addressing_mode::register_b },
	{ operation_type::ld_reg, {0xDD, 0x4B}, addressing_mode::register_e, addressing_mode::register_c },
	{ operation_type::ld_reg, {0xDD, 0x53}, addressing_mode::register_e, addressing_mode::register_d },
	{ operation_type::ld_reg, {0xDD, 0x5B}, addressing_mode::register_e, addressing_mode::register_e },
	{ operation_type::ld_reg, {0xDD, 0x63}, addressing_mode::register_e, addressing_mode::register_ixh },
	{ operation_type::ld_reg, {0xDD, 0x6B}, addressing_mode::register_e, addressing_mode::register_ixl },
	{ operation_type::ld_reg, {0xDD, 0x7C}, addressing_mode::register_ixh, addressing_mode::register_a },
	{ operation_type::ld_reg, {0xDD, 0x44}, addressing_mode::register_ixh, addressing_mode::register_b },
	{ operation_type::ld_reg, {0xDD, 0x4C}, addressing_mode::register_ixh, addressing_mode::register_c },
	{ operation_type::ld_reg, {0xDD, 0x54}, addressing_mode::register_ixh, addressing_mode::register_d },
	{ operation_type::ld_reg, {0xDD, 0x5C}, addressing_mode::register_ixh, addressing_mode::register_e },
	{ operation_type::ld_reg, {0xDD, 0x64}, addressing_mode::register_ixh, addressing_mode::register_ixh },
	{ operation_type::ld_reg, {0xDD, 0x6C}, addressing_mode::register_ixh, addressing_mode::register_ixl },
	{ operation_type::ld_reg, {0xDD, 0x7D}, addressing_mode::register_ixl, addressing_mode::register_a },
	{ operation_type::ld_reg, {0xDD, 0x45}, addressing_mode::register_ixl, addressing_mode::register_b },
	{ operation_type::ld_reg, {0xDD, 0x4D}, addressing_mode::register_ixl, addressing_mode::register_c },
	{ operation_type::ld_reg, {0xDD, 0x55}, addressing_mode::register_ixl, addressing_mode::register_d },
	{ operation_type::ld_reg, {0xDD, 0x5D}, addressing_mode::register_ixl, addressing_mode::register_e },
	{ operation_type::ld_reg, {0xDD, 0x65}, addressing_mode::register_ixl, addressing_mode::register_ixh },
	{ operation_type::ld_reg, {0xDD, 0x6D}, addressing_mode::register_ixl, addressing_mode::register_ixl },
	{ operation_type::ld_reg, {0xDD, 0x26}, addressing_mode::immediate, addressing_mode::register_ixh },
	{ operation_type::ld_reg, {0xDD, 0x2E}, addressing_mode::immediate, addressing_mode::register_ixl },
	{ operation_type::ld_reg, {0xDD, 0x7E}, addressing_mode::indexed_ix, addressing_mode::register_a },
	{ operation_type::ld_reg, {0xDD, 0x46}, addressing_mode::indexed_ix, addressing_mode::register_b },
	{ operation_type::ld_reg, {0xDD, 0x4E}, addressing_mode::indexed_ix, addressing_mode::register_c },
	{ operation_type::ld_reg, {0xDD, 0x56}, addressing_mode::indexed_ix, addressing_mode::register_d },
	{ operation_type::ld_reg, {0xDD, 0x5E}, addressing_mode::indexed_ix, addressing_mode::register_e },
	{ operation_type::ld_reg, {0xDD, 0x66}, addressing_mode::indexed_ix, addressing_mode::register_h },
	{ operation_type::ld_reg, {0xDD, 0x6E}, addressing_mode::indexed_ix, addressing_mode::register_l },
	{ operation_type::ld_reg, {0xED, 0x47}, addressing_mode::register_a, addressing_mode::register_i },
	{ operation_type::ld_reg, {0xED, 0x4F}, addressing_mode::register_a, addressing_mode::register_r },
	{ operation_type::ld_reg, {0xFD, 0x7F}, addressing_mode::register_a, addressing_mode::register_a },
	{ operation_type::ld_reg, {0xFD, 0x47}, addressing_mode::register_a, addressing_mode::register_b },
	{ operation_type::ld_reg, {0xFD, 0x4F}, addressing_mode::register_a, addressing_mode::register_c },
	{ operation_type::ld_reg, {0xFD, 0x57}, addressing_mode::register_a, addressing_mode::register_d },
	{ operation_type::ld_reg, {0xFD, 0x5F}, addressing_mode::register_a, addressing_mode::register_e },
	{ operation_type::ld_reg, {0xFD, 0x67}, addressing_mode::register_a, addressing_mode::register_iyh },
	{ operation_type::ld_reg, {0xFD, 0x6F}, addressing_mode::register_a, addressing_mode::register_iyl },
	{ operation_type::ld_reg, {0xFD, 0x78}, addressing_mode::register_b, addressing_mode::register_a },
	{ operation_type::ld_reg, {0xFD, 0x40}, addressing_mode::register_b, addressing_mode::register_b },
	{ operation_type::ld_reg, {0xFD, 0x48}, addressing_mode::register_b, addressing_mode::register_c },
	{ operation_type::ld_reg, {0xFD, 0x50}, addressing_mode::register_b, addressing_mode::register_d },
	{ operation_type::ld_reg, {0xFD, 0x58}, addressing_mode::register_b, addressing_mode::register_e },
	{ operation_type::ld_reg, {0xFD, 0x60}, addressing_mode::register_b, addressing_mode::register_iyh },
	{ operation_type::ld_reg, {0xFD, 0x68}, addressing_mode::register_b, addressing_mode::register_iyl },
	{ operation_type::ld_reg, {0xFD, 0x79}, addressing_mode::register_c, addressing_mode::register_a },
	{ operation_type::ld_reg, {0xFD, 0x41}, addressing_mode::register_c, addressing_mode::register_b },
	{ operation_type::ld_reg, {0xFD, 0x49}, addressing_mode::register_c, addressing_mode::register_c },
	{ operation_type::ld_reg, {0xFD, 0x51}, addressing_mode::register_c, addressing_mode::register_d },
	{ operation_type::ld_reg, {0xFD, 0x59}, addressing_mode::register_c, addressing_mode::register_e },
	{ operation_type::ld_reg, {0xFD, 0x61}, addressing_mode::register_c, addressing_mode::register_iyh },
	{ operation_type::ld_reg, {0xFD, 0x69}, addressing_mode::register_c, addressing_mode::register_iyl },
	{ operation_type::ld_reg, {0xFD, 0x7A}, addressing_mode::register_d, addressing_mode::register_a },
	{ operation_type::ld_reg, {0xFD, 0x42}, addressing_mode::register_d, addressing_mode::register_b },
	{ operation_type::ld_reg, {0xFD, 0x4A}, addressing_mode::register_d, addressing_mode::register_c },
	{ operation_type::ld_reg, {0xFD, 0x52}, addressing_mode::register_d, addressing_mode::register_d },
	{ operation_type::ld_reg, {0xFD, 0x5A}, addressing_mode::register_d, addressing_mode::register_e },
	{ operation_type::ld_reg, {0xFD, 0x62}, addressing_mode::register_d, addressing_mode::register_iyh },
	{ operation_type::ld_reg, {0xFD, 0x6A}, addressing_mode::register_d, addressing_mode::register_iyl },
	{ operation_type::ld_reg, {0xFD, 0x7B}, addressing_mode::register_e, addressing_mode::register_a },
	{ operation_type::ld_reg, {0xFD, 0x43}, addressing_mode::register_e, addressing_mode::register_b },
	{ operation_type::ld_reg, {0xFD, 0x4B}, addressing_mode::register_e, addressing_mode::register_c },
	{ operation_type::ld_reg, {0xFD, 0x53}, addressing_mode::register_e, addressing_mode::register_d },
	{ operation_type::ld_reg, {0xFD, 0x5B}, addressing_mode::register_e, addressing_mode::register_e },
	{ operation_type::ld_reg, {0xFD, 0x63}, addressing_mode::register_e, addressing_mode::register_iyh },
	{ operation_type::ld_reg, {0xFD, 0x6B}, addressing_mode::register_e, addressing_mode::register_iyl },
	{ operation_type::ld_reg, {0xFD, 0x7C}, addressing_mode::register_iyh, addressing_mode::register_a },
	{ operation_type::ld_reg, {0xFD, 0x44}, addressing_mode::register_iyh, addressing_mode::register_b },
	{ operation_type::ld_reg, {0xFD, 0x4C}, addressing_mode::register_iyh, addressing_mode::register_c },
	{ operation_type::ld_reg, {0xFD, 0x54}, addressing_mode::register_iyh, addressing_mode::register_d },
	{ operation_type::ld_reg, {0xFD, 0x5C}, addressing_mode::register_iyh, addressing_mode::register_e },
	{ operation_type::ld_reg, {0xFD, 0x64}, addressing_mode::register_iyh, addressing_mode::register_iyh },
	{ operation_type::ld_reg, {0xFD, 0x6C}, addressing_mode::register_iyh, addressing_mode::register_iyl },
	{ operation_type::ld_reg, {0xFD, 0x7D}, addressing_mode::register_iyl, addressing_mode::register_a },
	{ operation_type::ld_reg, {0xFD, 0x45}, addressing_mode::register_iyl, addressing_mode::register_b },
	{ operation_type::ld_reg, {0xFD, 0x4D}, addressing_mode::register_iyl, addressing_mode::register_c },
	{ operation_type::ld_reg, {0xFD, 0x55}, addressing_mode::register_iyl, addressing_mode::register_d },
	{ operation_type::ld_reg, {0xFD, 0x5D}, addressing_mode::register_iyl, addressing_mode::register_e },
	{ operation_type::ld_reg, {0xFD, 0x65}, addressing_mode::register_iyl, addressing_mode::register_iyh },
	{ operation_type::ld_reg, {0xFD, 0x6D}, addressing_mode::register_iyl, addressing_mode::register_iyl },
	{ operation_type::ld_reg, {0xFD, 0x26}, addressing_mode::immediate, addressing_mode::register_iyh },
	{ operation_type::ld_reg, {0xFD, 0x2E}, addressing_mode::immediate, addressing_mode::register_iyl },
	{ operation_type::ld_reg, {0xFD, 0x7E}, addressing_mode::indexed_iy, addressing_mode::register_a },
	{ operation_type::ld_reg, {0xFD, 0x46}, addressing_mode::indexed_iy, addressing_mode::register_b },
	{ operation_type::ld_reg, {0xFD, 0x4E}, addressing_mode::indexed_iy, addressing_mode::register_c },
	{ operation_type::ld_reg, {0xFD, 0x56}, addressing_mode::indexed_iy, addressing_mode::register_d },
	{ operation_type::ld_reg, {0xFD, 0x5E}, addressing_mode::indexed_iy, addressing_mode::register_e },
	{ operation_type::ld_reg, {0xFD, 0x66}, addressing_mode::indexed_iy, addressing_mode::register_h },
	{ operation_type::ld_reg, {0xFD, 0x6E}, addressing_mode::indexed_iy, addressing_mode::register_l },
	{ operation_type::ld_at, {0x32}, addressing_mode::register_a, addressing_mode::immediate_ext },
	{ operation_type::ld_at, {0x77}, addressing_mode::register_a, addressing_mode::indirect_hl },
	{ operation_type::ld_at, {0x02}, addressing_mode::register_a, addressing_mode::indirect_bc },
	{ operation_type::ld_at, {0x12}, addressing_mode::register_a, addressing_mode::indirect_de },
	{ operation_type::ld_at, {0x70}, addressing_mode::register_b, addressing_mode::indirect_hl },
	{ operation_type::ld_at, {0x71}, addressing_mode::register_c, addressing_mode::indirect_hl },
	{ operation_type::ld_at, {0x72}, addressing_mode::register_d, addressing_mode::indirect_hl },
	{ operation_type::ld_at, {0x73}, addressing_mode::register_e, addressing_mode::indirect_hl },
	{ operation_type::ld_at, {0x74}, addressing_mode::register_h, addressing_mode::indirect_hl },
	{ operation_type::ld_at, {0x75}, addressing_mode::register_l, addressing_mode::indirect_hl },
	{ operation_type::ld_at, {0x36}, addressing_mode::immediate, addressing_mode::indirect_hl },
	{ operation_type::ld_at, {0xDD, 0x77}, addressing_mode::register_a, addressing_mode::indexed_ix },
	{ operation_type::ld_at, {0xDD, 0x70}, addressing_mode::register_b, addressing_mode::indexed_ix },
	{ operation_type::ld_at, {0xDD, 0x71}, addressing_mode::register_c, addressing_mode::indexed_ix },
	{ operation_type::ld_at, {0xDD, 0x72}, addressing_mode::register_d, addressing_mode::indexed_ix },
	{ operation_type::ld_at, {0xDD, 0x73}, addressing_mode::register_e, addressing_mode::indexed_ix },
	{ operation_type::ld_at, {0xDD, 0x74}, addressing_mode::register_h, addressing_mode::indexed_ix },
	{ operation_type::ld_at, {0xDD, 0x75}, addressing_mode::register_l, addressing_mode::indexed_ix },
	{ operation_type::ld_at, {0xDD, 0x36}, addressing_mode::immediate, addressing_mode::indexed_ix },
	{ operation_type::ld_at, {0xFD, 0x77}, addressing_mode::register_a, addressing_mode::indexed_iy },
	{ operation_type::ld_at, {0xFD, 0x70}, addressing_mode::register_b, addressing_mode::indexed_iy },
	{ operation_type::ld_at, {0xFD, 0x71}, addressing_mode::register_c, addressing_mode::indexed_iy },
	{ operation_type::ld_at, {0xFD, 0x72}, addressing_mode::register_d, addressing_mode::indexed_iy },
	{ operation_type::ld_at, {0xFD, 0x73}, addressing_mode::register_e, addressing_mode::indexed_iy },
	{ operation_type::ld_at, {0xFD, 0x74}, addressing_mode::register_h, addressing_mode::indexed_iy },
	{ operation_type::ld_at, {0xFD, 0x75}, addressing_mode::register_l, addressing_mode::indexed_iy },
	{ operation_type::ld_at, {0xFD, 0x36}, addressing_mode::immediate, addressing_mode::indexed_iy },
	{ operation_type::ld_ir, {0xED, 0x57}, addressing_mode::register_i, addressing_mode::implied },
	{ operation_type::ld_ir, {0xED, 0x5F}, addressing_mode::register_r, addressing_mode::implied },
	{ operation_type::ld_16_reg, {0xF9}, addressing_mode::register_hl, addressing_mode::register_sp },
	{ operation_type::ld_16_reg, {0x01}, addressing_mode::immediate_ext, addressing_mode::register_bc },
	{ operation_type::ld_16_reg, {0x11}, addressing_mode::immediate_ext, addressing_mode::register_de },
	{ operation_type::ld_16_reg, {0x21}, addressing_mode::immediate_ext, addressing_mode::register_hl },
	{ operation_type::ld_16_reg, {0x31}, addressing_mode::immediate_ext, addressing_mode::register_sp },
	{ operation_type::ld_16_reg, {0xDD, 0xF9}, addressing_mode::register_ix, addressing_mode::register_sp },
	{ operation_type::ld_16_reg, {0xDD, 0x21}, addressing_mode::immediate_ext, addressing_mode::register_ix },
	{ operation_type::ld_16_reg, {0xFD, 0xF9}, addressing_mode::register_iy, addressing_mode::register_sp },
	{ operation_type::ld_16_reg, {0xFD, 0x21}, addressing_mode::immediate_ext, addressing_mode::register_iy },
	{ operation_type::ld_16_reg_from, {0x2A}, addressing_mode::immediate_ext, addressing_mode::register_hl },
	{ operation_type::ld_16_reg_from, {0xDD, 0x2A}, addressing_mode::immediate_ext, addressing_mode::register_ix },
	{ operation_type::ld_16_reg_from, {0xED, 0x4B}, addressing_mode::immediate_ext, addressing_mode::register_bc },
	{ operation_type::ld_16_reg_from, {0xED, 0x5B}, addressing_mode::immediate_ext, addressing_mode::register_de },
	{ operation_type::ld_16_reg_from, {0xED, 0x6B}, addressing_mode::immediate_ext, addressing_mode::register_hl },
	{ operation_type::ld_16_reg_from, {0xED, 0x7B}, addressing_mode::immediate_ext, addressing_mode::register_sp },
	{ operation_type::ld_16_reg_from, {0xFD, 0x2A}, addressing_mode::immediate_ext, addressing_mode::register_iy },
	{ operation_type::ld_16_at, {0x22}, addressing_mode::register_hl, addressing_mode::immediate_ext },
	{ operation_type::ld_16_at, {0xDD, 0x22}, addressing_mode::register_ix, addressing_mode::immediate_ext },
	{ operation_type::ld_16_at, {0xED, 0x43}, addressing_mode::register_bc, addressing_mode::immediate_ext },
	{ operation_type::ld_16_at, {0xED, 0x53}, addressing_mode::register_de, addressing_mode::immediate_ext },
	{ operation_type::ld_16_at, {0xED, 0x63}, addressing_mode::register_hl, addressing_mode::immediate_ext },
	{ operation_type::ld_16_at, {0xED, 0x73}, addressing_mode::register_sp, addressing_mode::immediate_ext },
	{ operation_type::ld_16_at, {0xFD, 0x22}, addressing_mode::register_iy, addressing_mode::immediate_ext },
	{ operation_type::push, {0xF5}, addressing_mode::register_af, addressing_mode::implied },
	{ operation_type::push, {0xC5}, addressing_mode::register_bc, addressing_mode::implied },
	{ operation_type::push, {0xD5}, addressing_mode::register_de, addressing_mode::implied },
	{ operation_type::push, {0xE5}, addressing_mode::register_hl, addressing_mode::implied },
	{ operation_type::push, {0xDD, 0xE5}, addressing_mode::register_ix, addressing_mode::implied },
	{ operation_type::push, {0xFD, 0xE5}, addressing_mode::register_iy, addressing_mode::implied },
	{ operation_type::pop, {0xF1}, addressing_mode::implied, addressing_mode::register_af },
	{ operation_type::pop, {0xC1}, addressing_mode::implied, addressing_mode::register_bc },
	{ operation_type::pop, {0xD1}, addressing_mode::implied, addressing_mode::register_de },
	{ operation_type::pop, {0xE1}, addressing_mode::implied, addressing_mode::register_hl },
	{ operation_type::pop, {0xDD, 0xE1}, addressing_mode::implied, addressing_mode::register_ix },
	{ operation_type::pop, {0xFD, 0xE1}, addressing_mode::implied, addressing_mode::register_iy },
	{ operation_type::call, {0xCD}, addressing_mode::immediate_ext, addressing_mode::none },
	{ operation_type::call_cc, {0xFC}, addressing_mode::immediate_ext, addressing_mode::none },
	{ operation_type::call_cc, {0xF4}, addressing_mode::immediate_ext, addressing_mode::none },
	{ operation_type::call_cc, {0xEC}, addressing_mode::immediate_ext, addressing_mode::none },
	{ operation_type::call_cc, {0xE4}, addressing_mode::immediate_ext, addressing_mode::none },
	{ operation_type::call_cc, {0xDC}, addressing_mode::immediate_ext, addressing_mode::none },
	{ operation_type::call_cc, {0xD4}, addressing_mode::immediate_ext, addressing_mode::none },
	{ operation_type::call_cc, {0xCC}, addressing_mode::immediate_ext, addressing_mode::none },
	{ operation_type::call_cc, {0xC4}, addressing_mode::immediate_ext, addressing_mode::none },
	{ operation_type::rst, {0xC7}, addressing_mode::none, addressing_mode::none },
	{ operation_type::rst, {0xCF}, addressing_mode::none, addressing_mode::none },
	{ operation_type::rst, {0xD7}, addressing_mode::none, addressing_mode::none },
	{ operation_type::rst, {0xDF}, addressing_mode::none, addressing_mode::none },
	{ operation_type::rst, {0xE7}, addressing_mode::none, addressing_mode::none },
	{ operation_type::rst, {0xEF}, addressing_mode::none, addressing_mode::none },
	{ operation_type::rst, {0xF7}, addressing_mode::none, addressing_mode::none },
	{ operation_type::rst, {0xFF}, addressing_mode::none, addressing_mode::none },
	{ operation_type::ret, {0xC9}, addressing_mode::none, addressing_mode::none },
	{ operation_type::reti, {0xED, 0x4D}, addressing_mode::none, addressing_mode::none },
	{ operation_type::retn, {0xED, 0x45}, addressing_mode::none, addressing_mode::none },
	{ operation_type::ret_cc, {0xC8}, addressing_mode::none, addressing_mode::none },
	{ operation_type::ret_cc, {0xC0}, addressing_mode::none, addressing_mode::none },
	{ operation_type::ret_cc, {0xF8}, addressing_mode::none, addressing_mode::none },
	{ operation_type::ret_cc, {0xF0}, addressing_mode::none, addressing_mode::none },
	{ operation_type::ret_cc, {0xE8}, addressing_mode::none, addressing_mode::none },
	{ operation_type::ret_cc, {0xD8}, addressing_mode::none, addressing_mode::none },
	{ operation_type::ret_cc, {0xD0}, addressing_mode::none, addressing_mode::none },
	{ operation_type::ret_cc, {0xE0}, addressing_mode::none, addressing_mode::none },
	{ operation_type::jp, {0xE9}, addressing_mode::register_hl, addressing_mode::none },
	{ operation_type::jp, {0xC3}, addressing_mode::immediate_ext, addressing_mode::none },
	{ operation_type::jp, {0xDD, 0xE9}, addressing_mode::register_ix, addressing_mode::none },
	{ operation_type::jp, {0xFD, 0xE9}, addressing_mode::register_iy, addressing_mode::none },
	{ operation_type::jp_cc, {0xDA}, addressing_mode::immediate_ext, addressing_mode::none },
	{ operation_type::jp_cc, {0xFA}, addressing_mode::immediate_ext, addressing_mode::none },
	{ operation_type::jp_cc, {0xF2}, addressing_mode::immediate_ext, addressing_mode::none },
	{ operation_type::jp_cc, {0xEA}, addressing_mode::immediate_ext, addressing_mode::none },
	{ operation_type::jp_cc, {0xE2}, addressing_mode::immediate_ext, addressing_mode::none },
	{ operation_type::jp_cc, {0xD2}, addressing_mode::immediate_ext, addressing_mode::none },
	{ operation_type::jp_cc, {0xCA}, addressing_mode::immediate_ext, addressing_mode::none },
	{ operation_type::jp_cc, {0xC2}, addressing_mode::immediate_ext, addressing_mode::none },
	{ operation_type::jr_z, {0x28}, addressing_mode::immediate, addressing_mode::none },
	{ operation_type::jr_nz, {0x20}, addressing_mode::immediate, addressing_mode::none },
	{ operation_type::jr_c, {0x38}, addressing_mode::immediate, addressing_mode::none },
	{ operation_type::jr_nc, {0x30}, addressing_mode::immediate, addressing_mode::none },
	{ operation_type::jr, {0x18}, addressing_mode::immediate, addressing_mode::none },
	{ operation_type::djnz, {0x10}, addressing_mode::immediate, addressing_mode::none },
	{ operation_type::in, {0xDB}, addressing_mode::immediate, addressing_mode::none },
	{ operation_type::in_reg, {0xED, 0x78}, addressing_mode::none, addressing_mode::register_a },
	{ operation_type::in_reg, {0xED, 0x40}, addressing_mode::none, addressing_mode::register_b },
	{ operation_type::in_reg, {0xED, 0x48}, addressing_mode::none, addressing_mode::register_c },
	{ operation_type::in_reg, {0xED, 0x50}, addressing_mode::none, addressing_mode::register_d },
	{ operation_type::in_reg, {0xED, 0x58}, addressing_mode::none, addressing_mode::register_e },
	{ operation_type::in_reg, {0xED, 0x60}, addressing_mode::none, addressing_mode::register_h },
	{ operation_type::in_reg, {0xED, 0x68}, addressing_mode::none, addressing_mode::register_l },
	{ operation_type::ini, {0xED, 0xA2}, addressing_mode::none, addressing_mode::none },
	{ operation_type::inir, {0xED, 0xB2}, addressing_mode::none, addressing_mode::none },
	{ operation_type::ind, {0xED, 0xAA}, addressing_mode::none, addressing_mode::none },
	{ operation_type::indr, {0xED, 0xBA}, addressing_mode::none, addressing_mode::none },
	{ operation_type::out, {0xD3}, addressing_mode::immediate, addressing_mode::none },
	{ operation_type::out_reg, {0xED, 0x79}, addressing_mode::register_a, addressing_mode::none },
	{ operation_type::out_reg, {0xED, 0x41}, addressing_mode::register_b, addressing_mode::none },
	{ operation_type::out_reg, {0xED, 0x49}, addressing_mode::register_c, addressing_mode::none },
	{ operation_type::out_reg, {0xED, 0x51}, addressing_mode::register_d, addressing_mode::none },
	{ operation_type::out_reg, {0xED, 0x59}, addressing_mode::register_e, addressing_mode::none },
	{ operation_type::out_reg, {0xED, 0x61}, addressing_mode::register_h, addressing_mode::none },
	{ operation_type::out_reg, {0xED, 0x69}, addressing_mode::register_l, addressing_mode::none },
	{ operation_type::outi, {0xED, 0xA3}, addressing_mode::none, addressing_mode::none },
	{ operation_type::otir, {0xED, 0xB3}, addressing_mode::none, addressing_mode::none },
	{ operation_type::outd, {0xED, 0xAB}, addressing_mode::none, addressing_mode::none },
	{ operation_type::otdr, {0xED, 0xBB}, addressing_mode::none, addressing_mode::none },
	{ operation_type::ex_de_hl, {0xEB}, addressing_mode::implied, addressing_mode::implied },
	{ operation_type::ex_af_afs, {0x08}, addressing_mode::implied, addressing_mode::implied },
	{ operation_type::exx, {0xD9}, addressing_mode::implied, addressing_mode::implied },
	{ operation_type::ex_16_at, {0xE3}, addressing_mode::register_hl, addressing_mode::indirect_sp },
	{ operation_type::ex_16_at, {0xDD, 0xE3}, addressing_mode::register_ix, addressing_mode::indirect_sp },
	{ operation_type::ex_16_at, {0xFD, 0xE3}, addressing_mode::register_iy, addressing_mode::indirect_sp },
	{ operation_type::ldi, {0xED, 0xA0}, addressing_mode::implied, addressing_mode::implied },
	{ operation_type::ldir, {0xED, 0xB0}, addressing_mode::implied, addressing_mode::implied },
	{ operation_type::cpd, {0xED, 0xA9}, addressing_mode::implied, addressing_mode::implied },
	{ operation_type::cpdr, {0xED, 0xB9}, addressing_mode::implied, addressing_mode::implied },
	{ operation_type::cpi, {0xED, 0xA1}, addressing_mode::implied, addressing_mode::implied },
	{ operation_type::cpir, {0xED, 0xB1}, addressing_mode::implied, addressing_mode::implied },
	{ operation_type::ldd, {0xED, 0xA8}, addressing_mode::implied, addressing_mode::implied },
	{ operation_type::lddr, {0xED, 0xB8}, addressing_mode::implied, addressing_mode::implied },
	{ operation_type::rlca, {0x07}, addressing_mode::implied, addressing_mode::implied },
	{ operation_type::rrca, {0x0F}, addressing_mode::implied, addressing_mode::implied },
	{ operation_type::rla, {0x17}, addressing_mode::implied, addressing_mode::implied },
	{ operation_type::rra, {0x1F}, addressing_mode::implied, addressing_mode::implied },
	{ operation_type::rld, {0xED, 0x6F}, addressing_mode::implied, addressing_mode::implied },
	{ operation_type::rrd, {0xED, 0x67}, addressing_mode::implied, addressing_mode::implied },
	{ operation_type::rlc, {0xCB, 0x07}, addressing_mode::implied, addressing_mode::register_a },
	{ operation_type::rlc, {0xCB, 0x00}, addressing_mode::implied, addressing_mode::register_b },
	{ operation_type::rlc, {0xCB, 0x01}, addressing_mode::implied, addressing_mode::register_c },
	{ operation_type::rlc, {0xCB, 0x02}, addressing_mode::implied, addressing_mode::register_d },
	{ operation_type::rlc, {0xCB, 0x03}, addressing_mode::implied, addressing_mode::register_e },
	{ operation_type::rlc, {0xCB, 0x04}, addressing_mode::implied, addressing_mode::register_h },
	{ operation_type::rlc, {0xCB, 0x05}, addressing_mode::implied, addressing_mode::register_l },
	{ operation_type::rlc_at, {0xCB, 0x06}, addressing_mode::indirect_hl, addressing_mode::indirect_hl },
	{ operation_type::rrc, {0xCB, 0x0F}, addressing_mode::implied, addressing_mode::register_a },
	{ operation_type::rrc, {0xCB, 0x08}, addressing_mode::implied, addressing_mode::register_b },
	{ operation_type::rrc, {0xCB, 0x09}, addressing_mode::implied, addressing_mode::register_c },
	{ operation_type::rrc, {0xCB, 0x0A}, addressing_mode::implied, addressing_mode::register_d },
	{ operation_type::rrc, {0xCB, 0x0B}, addressing_mode::implied, addressing_mode::register_e },
	{ operation_type::rrc, {0xCB, 0x0C}, addressing_mode::implied, addressing_mode::register_h },
	{ operation_type::rrc, {0xCB, 0x0D}, addressing_mode::implied, addressing_mode::register_l },
	{ operation_type::rrc_at, {0xCB, 0x0E}, addressing_mode::indirect_hl, addressing_mode::indirect_hl },
	{ operation_type::rl, {0xCB, 0x17}, addressing_mode::implied, addressing_mode::register_a },
	{ operation_type::rl, {0xCB, 0x10}, addressing_mode::implied, addressing_mode::register_b },
	{ operation_type::rl, {0xCB, 0x11}, addressing_mode::implied, addressing_mode::register_c },
	{ operation_type::rl, {0xCB, 0x12}, addressing_mode::implied, addressing_mode::register_d },
	{ operation_type::rl, {0xCB, 0x13}, addressing_mode::implied, addressing_mode::register_e },
	{ operation_type::rl, {0xCB, 0x14}, addressing_mode::implied, addressing_mode::register_h },
	{ operation_type::rl, {0xCB, 0x15}, addressing_mode::implied, addressing_mode::register_l },
	{ operation_type::rl_at, {0xCB, 0x16}, addressing_mode::indirect_hl, addressing_mode::indirect_hl },
	{ operation_type::rr, {0xCB, 0x1F}, addressing_mode::implied, addressing_mode::register_a },
	{ operation_type::rr, {0xCB, 0x18}, addressing_mode::implied, addressing_mode::register_b },
	{ operation_type::rr, {0xCB, 0x19}, addressing_mode::implied, addressing_mode::register_c },
	{ operation_type::rr, {0xCB, 0x1A}, addressing_mode::implied, addressing_mode::register_d },
	{ operation_type::rr, {0xCB, 0x1B}, addressing_mode::implied, addressing_mode::register_e },
	{ operation_type::rr, {0xCB, 0x1C}, addressing_mode::implied, addressing_mode::register_h },
	{ operation_type::rr, {0xCB, 0x1D}, addressing_mode::implied, addressing_mode::register_l },
	{ operation_type::rr_at, {0xCB, 0x1E}, addressing_mode::indirect_hl, addressing_mode::indirect_hl },
	{ operation_type::sla, {0xCB, 0x27}, addressing_mode::implied, addressing_mode::register_a },
	{ operation_type::sla, {0xCB, 0x20}, addressing_mode::implied, addressing_mode::register_b },
	{ operation_type::sla, {0xCB, 0x21}, addressing_mode::implied, addressing_mode::register_c },
	{ operation_type::sla, {0xCB, 0x22}, addressing_mode::implied, addressing_mode::register_d },
	{ operation_type::sla, {0xCB, 0x23}, addressing_mode::implied, addressing_mode::register_e },
	{ operation_type::sla, {0xCB, 0x24}, addressing_mode::implied, addressing_mode::register_h },
	{ operation_type::sla, {0xCB, 0x25}, addressing_mode::implied, addressing_mode::register_l },
	{ operation_type::sla_at, {0xCB, 0x26}, addressing_mode::indirect_hl, addressing_mode::indirect_hl },
	{ operation_type::sra, {0xCB, 0x2F}, addressing_mode::implied, addressing_mode::register_a },
	{ operation_type::sra, {0xCB, 0x28}, addressing_mode::implied, addressing_mode::register_b },
	{ operation_type::sra, {0xCB, 0x29}, addressing_mode::implied, addressing_mode::register_c },
	{ operation_type::sra, {0xCB, 0x2A}, addressing_mode::implied, addressing_mode::register_d },
	{ operation_type::sra, {0xCB, 0x2B}, addressing_mode::implied, addressing_mode::register_e },
	{ operation_type::sra, {0xCB, 0x2C}, addressing_mode::implied, addressing_mode::register_h },
	{ operation_type::sra, {0xCB, 0x2D}, addressing_mode::implied, addressing_mode::register_l },
	{ operation_type::sra_at, {0xCB, 0x2E}, addressing_mode::indirect_hl, addressing_mode::indirect_hl },
	{ operation_type::srl, {0xCB, 0x3F}, addressing_mode::implied, addressing_mode::register_a },
	{ operation_type::srl, {0xCB, 0x38}, addressing_mode::implied, addressing_mode::register_b },
	{ operation_type::srl, {0xCB, 0x39}, addressing_mode::implied, addressing_mode::register_c },
	{ operation_type::srl, {0xCB, 0x3A}, addressing_mode::implied, addressing_mode::register_d },
	{ operation_type::srl, {0xCB, 0x3B}, addressing_mode::implied, addressing_mode::register_e },
	{ operation_type::srl, {0xCB, 0x3C}, addressing_mode::implied, addressing_mode::register_h },
	{ operation_type::srl, {0xCB, 0x3D}, addressing_mode::implied, addressing_mode::register_l },
	{ operation_type::srl_at, {0xCB, 0x3E}, addressing_mode::indirect_hl, addressing_mode::indirect_hl },
	{ operation_type::sll, {0xCB, 0x37}, addressing_mode::implied, addressing_mode::register_a },
	{ operation_type::sll, {0xCB, 0x30}, addressing_mode::implied, addressing_mode::register_b },
	{ operation_type::sll, {0xCB, 0x31}, addressing_mode::implied, addressing_mode::register_c },
	{ operation_type::sll, {0xCB, 0x32}, addressing_mode::implied, addressing_mode::register_d },
	{ operation_type::sll, {0xCB, 0x33}, addressing_mode::implied, addressing_mode::register_e },
	{ operation_type::sll, {0xCB, 0x34}, addressing_mode::implied, addressing_mode::register_h },
	{ operation_type::sll, {0xCB, 0x35}, addressing_mode::implied, addressing_mode::register_l },
	{ operation_type::sll_at, {0xCB, 0x36}, addressing_mode::indirect_hl, addressing_mode::indirect_hl },
	{ operation_type::tst_bit, {0xCB, 0x47}, addressing_mode::bit, addressing_mode::register_a },
	{ operation_type::tst_bit, {0xCB, 0x57}, addressing_mode::bit, addressing_mode::register_a },
	{ operation_type::tst_bit, {0xCB, 0x6F}, addressing_mode::bit, addressing_mode::register_a },
	{ operation_type::tst_bit, {0xCB, 0x77}, addressing_mode::bit, addressing_mode::register_a },
	{ operation_type::tst_bit, {0xCB, 0x4F}, addressing_mode::bit, addressing_mode::register_a },
	{ operation_type::tst_bit, {0xCB, 0x67}, addressing_mode::bit, addressing_mode::register_a },
	{ operation_type::tst_bit, {0xCB, 0x7F}, addressing_mode::bit, addressing_mode::register_a },
	{ operation_type::tst_bit, {0xCB, 0x5F}, addressing_mode::bit, addressing_mode::register_a },
	{ operation_type::tst_bit, {0xCB, 0x50}, addressing_mode::bit, addressing_mode::register_b },
	{ operation_type::tst_bit, {0xCB, 0x60}, addressing_mode::bit, addressing_mode::register_b },
	{ operation_type::tst_bit, {0xCB, 0x68}, addressing_mode::bit, addressing_mode::register_b },
	{ operation_type::tst_bit, {0xCB, 0x70}, addressing_mode::bit, addressing_mode::register_b },
	{ operation_type::tst_bit, {0xCB, 0x48}, addressing_mode::bit, addressing_mode::register_b },
	{ operation_type::tst_bit, {0xCB, 0x58}, addressing_mode::bit, addressing_mode::register_b },
	{ operation_type::tst_bit, {0xCB, 0x40}, addressing_mode::bit, addressing_mode::register_b },
	{ operation_type::tst_bit, {0xCB, 0x78}, addressing_mode::bit, addressing_mode::register_b },
	{ operation_type::tst_bit, {0xCB, 0x69}, addressing_mode::bit, addressing_mode::register_c },
	{ operation_type::tst_bit, {0xCB, 0x49}, addressing_mode::bit, addressing_mode::register_c },
	{ operation_type::tst_bit, {0xCB, 0x41}, addressing_mode::bit, addressing_mode::register_c },
	{ operation_type::tst_bit, {0xCB, 0x61}, addressing_mode::bit, addressing_mode::register_c },
	{ operation_type::tst_bit, {0xCB, 0x51}, addressing_mode::bit, addressing_mode::register_c },
	{ operation_type::tst_bit, {0xCB, 0x79}, addressing_mode::bit, addressing_mode::register_c },
	{ operation_type::tst_bit, {0xCB, 0x59}, addressing_mode::bit, addressing_mode::register_c },
	{ operation_type::tst_bit, {0xCB, 0x71}, addressing_mode::bit, addressing_mode::register_c },
	{ operation_type::tst_bit, {0xCB, 0x6A}, addressing_mode::bit, addressing_mode::register_d },
	{ operation_type::tst_bit, {0xCB, 0x7A}, addressing_mode::bit, addressing_mode::register_d },
	{ operation_type::tst_bit, {0xCB, 0x62}, addressing_mode::bit, addressing_mode::register_d },
	{ operation_type::tst_bit, {0xCB, 0x42}, addressing_mode::bit, addressing_mode::register_d },
	{ operation_type::tst_bit, {0xCB, 0x5A}, addressing_mode::bit, addressing_mode::register_d },
	{ operation_type::tst_bit, {0xCB, 0x72}, addressing_mode::bit, addressing_mode::register_d },
	{ operation_type::tst_bit, {0xCB, 0x52}, addressing_mode::bit, addressing_mode::register_d },
	{ operation_type::tst_bit, {0xCB, 0x4A}, addressing_mode::bit, addressing_mode::register_d },
	{ operation_type::tst_bit, {0xCB, 0x5B}, addressing_mode::bit, addressing_mode::register_e },
	{ operation_type::tst_bit, {0xCB, 0x7B}, addressing_mode::bit, addressing_mode::register_e },
	{ operation_type::tst_bit, {0xCB, 0x53}, addressing_mode::bit, addressing_mode::register_e },
	{ operation_type::tst_bit, {0xCB, 0x73}, addressing_mode::bit, addressing_mode::register_e },
	{ operation_type::tst_bit, {0xCB, 0x43}, addressing_mode::bit, addressing_mode::register_e },
	{ operation_type::tst_bit, {0xCB, 0x63}, addressing_mode::bit, addressing_mode::register_e },
	{ operation_type::tst_bit, {0xCB, 0x6B}, addressing_mode::bit, addressing_mode::register_e },
	{ operation_type::tst_bit, {0xCB, 0x4B}, addressing_mode::bit, addressing_mode::register_e },
	{ operation_type::tst_bit, {0xCB, 0x54}, addressing_mode::bit, addressing_mode::register_h },
	{ operation_type::tst_bit, {0xCB, 0x7C}, addressing_mode::bit, addressing_mode::register_h },
	{ operation_type::tst_bit, {0xCB, 0x74}, addressing_mode::bit, addressing_mode::register_h },
	{ operation_type::tst_bit, {0xCB, 0x6C}, addressing_mode::bit, addressing_mode::register_h },
	{ operation_type::tst_bit, {0xCB, 0x44}, addressing_mode::bit, addressing_mode::register_h },
	{ operation_type::tst_bit, {0xCB, 0x64}, addressing_mode::bit, addressing_mode::register_h },
	{ operation_type::tst_bit, {0xCB, 0x5C}, addressing_mode::bit, addressing_mode::register_h },
	{ operation_type::tst_bit, {0xCB, 0x4C}, addressing_mode::bit, addressing_mode::register_h },
	{ operation_type::tst_bit, {0xCB, 0x5D}, addressing_mode::bit, addressing_mode::register_l },
	{ operation_type::tst_bit, {0xCB, 0x7D}, addressing_mode::bit, addressing_mode::register_l },
	{ operation_type::tst_bit, {0xCB, 0x55}, addressing_mode::bit, addressing_mode::register_l },
	{ operation_type::tst_bit, {0xCB, 0x75}, addressing_mode::bit, addressing_mode::register_l },
	{ operation_type::tst_bit, {0xCB, 0x45}, addressing_mode::bit, addressing_mode::register_l },
	{ operation_type::tst_bit, {0xCB, 0x4D}, addressing_mode::bit, addressing_mode::register_l },
	{ operation_type::tst_bit, {0xCB, 0x6D}, addressing_mode::bit, addressing_mode::register_l },
	{ operation_type::tst_bit, {0xCB, 0x65}, addressing_mode::bit, addressing_mode::register_l },
	{ operation_type::tst_bit_at, {0xCB, 0x66}, addressing_mode::bit, addressing_mode::indirect_hl },
	{ operation_type::tst_bit_at, {0xCB, 0x76}, addressing_mode::bit, addressing_mode::indirect_hl },
	{ operation_type::tst_bit_at, {0xCB, 0x5E}, addressing_mode::bit, addressing_mode::indirect_hl },
	{ operation_type::tst_bit_at, {0xCB, 0x56}, addressing_mode::bit, addressing_mode::indirect_hl },
	{ operation_type::tst_bit_at, {0xCB, 0x4E}, addressing_mode::bit, addressing_mode::indirect_hl },
	{ operation_type::tst_bit_at, {0xCB, 0x7E}, addressing_mode::bit, addressing_mode::indirect_hl },
	{ operation_type::tst_bit_at, {0xCB, 0x6E}, addressing_mode::bit, addressing_mode::indirect_hl },
	{ operation_type::tst_bit_at, {0xCB, 0x46}, addressing_mode::bit, addressing_mode::indirect_hl },
	{ operation_type::set_bit, {0xCB, 0xD7}, addressing_mode::bit, addressing_mode::register_a },
	{ operation_type::set_bit, {0xCB, 0xEF}, addressing_mode::bit, addressing_mode::register_a },
	{ operation_type::set_bit, {0xCB, 0xE7}, addressing_mode::bit, addressing_mode::register_a },
	{ operation_type::set_bit, {0xCB, 0xDF}, addressing_mode::bit, addressing_mode::register_a },
	{ operation_type::set_bit, {0xCB, 0xF7}, addressing_mode::bit, addressing_mode::register_a },
	{ operation_type::set_bit, {0xCB, 0xCF}, addressing_mode::bit, addressing_mode::register_a },
	{ operation_type::set_bit, {0xCB, 0xC7}, addressing_mode::bit, addressing_mode::register_a },
	{ operation_type::set_bit, {0xCB, 0xFF}, addressing_mode::bit, addressing_mode::register_a },
	{ operation_type::set_bit, {0xCB, 0xC0}, addressing_mode::bit, addressing_mode::register_b },
	{ operation_type::set_bit, {0xCB, 0xE8}, addressing_mode::bit, addressing_mode::register_b },
	{ operation_type::set_bit, {0xCB, 0xE0}, addressing_mode::bit, addressing_mode::register_b },
	{ operation_type::set_bit, {0xCB, 0xF8}, addressing_mode::bit, addressing_mode::register_b },
	{ operation_type::set_bit, {0xCB, 0xD8}, addressing_mode::bit, addressing_mode::register_b },
	{ operation_type::set_bit, {0xCB, 0xD0}, addressing_mode::bit, addressing_mode::register_b },
	{ operation_type::set_bit, {0xCB, 0xF0}, addressing_mode::bit, addressing_mode::register_b },
	{ operation_type::set_bit, {0xCB, 0xC8}, addressing_mode::bit, addressing_mode::register_b },
	{ operation_type::set_bit, {0xCB, 0xC9}, addressing_mode::bit, addressing_mode::register_c },
	{ operation_type::set_bit, {0xCB, 0xC1}, addressing_mode::bit, addressing_mode::register_c },
	{ operation_type::set_bit, {0xCB, 0xF1}, addressing_mode::bit, addressing_mode::register_c },
	{ operation_type::set_bit, {0xCB, 0xE9}, addressing_mode::bit, addressing_mode::register_c },
	{ operation_type::set_bit, {0xCB, 0xD9}, addressing_mode::bit, addressing_mode::register_c },
	{ operation_type::set_bit, {0xCB, 0xD1}, addressing_mode::bit, addressing_mode::register_c },
	{ operation_type::set_bit, {0xCB, 0xF9}, addressing_mode::bit, addressing_mode::register_c },
	{ operation_type::set_bit, {0xCB, 0xE1}, addressing_mode::bit, addressing_mode::register_c },
	{ operation_type::set_bit, {0xCB, 0xEA}, addressing_mode::bit, addressing_mode::register_d },
	{ operation_type::set_bit, {0xCB, 0xC2}, addressing_mode::bit, addressing_mode::register_d },
	{ operation_type::set_bit, {0xCB, 0xDA}, addressing_mode::bit, addressing_mode::register_d },
	{ operation_type::set_bit, {0xCB, 0xFA}, addressing_mode::bit, addressing_mode::register_d },
	{ operation_type::set_bit, {0xCB, 0xE2}, addressing_mode::bit, addressing_mode::register_d },
	{ operation_type::set_bit, {0xCB, 0xD2}, addressing_mode::bit, addressing_mode::register_d },
	{ operation_type::set_bit, {0xCB, 0xF2}, addressing_mode::bit, addressing_mode::register_d },
	{ operation_type::set_bit, {0xCB, 0xCA}, addressing_mode::bit, addressing_mode::register_d },
	{ operation_type::set_bit, {0xCB, 0xE3}, addressing_mode::bit, addressing_mode::register_e },
	{ operation_type::set_bit, {0xCB, 0xC3}, addressing_mode::bit, addressing_mode::register_e },
	{ operation_type::set_bit, {0xCB, 0xF3}, addressing_mode::bit, addressing_mode::register_e },
	{ operation_type::set_bit, {0xCB, 0xEB}, addressing_mode::bit, addressing_mode::register_e },
	{ operation_type::set_bit, {0xCB, 0xDB}, addressing_mode::bit, addressing_mode::register_e },
	{ operation_type::set_bit, {0xCB, 0xD3}, addressing_mode::bit, addressing_mode::register_e },
	{ operation_type::set_bit, {0xCB, 0xFB}, addressing_mode::bit, addressing_mode::register_e },
	{ operation_type::set_bit, {0xCB, 0xCB}, addressing_mode::bit, addressing_mode::register_e },
	{ operation_type::set_bit, {0xCB, 0xEC}, addressing_mode::bit, addressing_mode::register_h },
	{ operation_type::set_bit, {0xCB, 0xF4}, addressing_mode::bit, addressing_mode::register_h },
	{ operation_type::set_bit, {0xCB, 0xFC}, addressing_mode::bit, addressing_mode::register_h },
	{ operation_type::set_bit, {0xCB, 0xE4}, addressing_mode::bit, addressing_mode::register_h },
	{ operation_type::set_bit, {0xCB, 0xC4}, addressing_mode::bit, addressing_mode::register_h },
	{ operation_type::set_bit, {0xCB, 0xCC}, addressing_mode::bit, addressing_mode::register_h },
	{ operation_type::set_bit, {0xCB, 0xD4}, addressing_mode::bit, addressing_mode::register_h },
	{ operation_type::set_bit, {0xCB, 0xDC}, addressing_mode::bit, addressing_mode::register_h },
	{ operation_type::set_bit, {0xCB, 0xD5}, addressing_mode::bit, addressing_mode::register_l },
	{ operation_type::set_bit, {0xCB, 0xED}, addressing_mode::bit, addressing_mode::register_l },
	{ operation_type::set_bit, {0xCB, 0xCD}, addressing_mode::bit, addressing_mode::register_l },
	{ operation_type::set_bit, {0xCB, 0xDD}, addressing_mode::bit, addressing_mode::register_l },
	{ operation_type::set_bit, {0xCB, 0xC5}, addressing_mode::bit, addressing_mode::register_l },
	{ operation_type::set_bit, {0xCB, 0xF5}, addressing_mode::bit, addressing_mode::register_l },
	{ operation_type::set_bit, {0xCB, 0xE5}, addressing_mode::bit, addressing_mode::register_l },
	{ operation_type::set_bit, {0xCB, 0xFD}, addressing_mode::bit, addressing_mode::register_l },
	{ operation_type::set_bit_at, {0xCB, 0xFE}, addressing_mode::bit, addressing_mode::indirect_hl },
	{ operation_type::set_bit_at, {0xCB, 0xF6}, addressing_mode::bit, addressing_mode::indirect_hl },
	{ operation_type::set_bit_at, {0xCB, 0xEE}, addressing_mode::bit, addressing_mode::indirect_hl },
	{ operation_type::set_bit_at, {0xCB, 0xE6}, addressing_mode::bit, addressing_mode::indirect_hl },
	{ operation_type::set_bit_at, {0xCB, 0xDE}, addressing_mode::bit, addressing_mode::indirect_hl },
	{ operation_type::set_bit_at, {0xCB, 0xD6}, addressing_mode::bit, addressing_mode::indirect_hl },
	{ operation_type::set_bit_at, {0xCB, 0xCE}, addressing_mode::bit, addressing_mode::indirect_hl },
	{ operation_type::set_bit_at, {0xCB, 0xC6}, addressing_mode::bit, addressing_mode::indirect_hl },
	{ operation_type::res_bit, {0xCB, 0x8F}, addressing_mode::bit, addressing_mode::register_a },
	{ operation_type::res_bit, {0xCB, 0x97}, addressing_mode::bit, addressing_mode::register_a },
	{ operation_type::res_bit, {0xCB, 0xA7}, addressing_mode::bit, addressing_mode::register_a },
	{ operation_type::res_bit, {0xCB, 0xAF}, addressing_mode::bit, addressing_mode::register_a },
	{ operation_type::res_bit, {0xCB, 0xB7}, addressing_mode::bit, addressing_mode::register_a },
	{ operation_type::res_bit, {0xCB, 0xBF}, addressing_mode::bit, addressing_mode::register_a },
	{ operation_type::res_bit, {0xCB, 0x9F}, addressing_mode::bit, addressing_mode::register_a },
	{ operation_type::res_bit, {0xCB, 0x87}, addressing_mode::bit, addressing_mode::register_a },
	{ operation_type::res_bit, {0xCB, 0x80}, addressing_mode::bit, addressing_mode::register_b },
	{ operation_type::res_bit, {0xCB, 0xA0}, addressing_mode::bit, addressing_mode::register_b },
	{ operation_type::res_bit, {0xCB, 0xA8}, addressing_mode::bit, addressing_mode::register_b },
	{ operation_type::res_bit, {0xCB, 0x98}, addressing_mode::bit, addressing_mode::register_b },
	{ operation_type::res_bit, {0xCB, 0xB0}, addressing_mode::bit, addressing_mode::register_b },
	{ operation_type::res_bit, {0xCB, 0x90}, addressing_mode::bit, addressing_mode::register_b },
	{ operation_type::res_bit, {0xCB, 0xB8}, addressing_mode::bit, addressing_mode::register_b },
	{ operation_type::res_bit, {0xCB, 0x88}, addressing_mode::bit, addressing_mode::register_b },
	{ operation_type::res_bit, {0xCB, 0x89}, addressing_mode::bit, addressing_mode::register_c },
	{ operation_type::res_bit, {0xCB, 0x81}, addressing_mode::bit, addressing_mode::register_c },
	{ operation_type::res_bit, {0xCB, 0x99}, addressing_mode::bit, addressing_mode::register_c },
	{ operation_type::res_bit, {0xCB, 0xA9}, addressing_mode::bit, addressing_mode::register_c },
	{ operation_type::res_bit, {0xCB, 0xA1}, addressing_mode::bit, addressing_mode::register_c },
	{ operation_type::res_bit, {0xCB, 0x91}, addressing_mode::bit, addressing_mode::register_c },
	{ operation_type::res_bit, {0xCB, 0xB1}, addressing_mode::bit, addressing_mode::register_c },
	{ operation_type::res_bit, {0xCB, 0xB9}, addressing_mode::bit, addressing_mode::register_c },
	{ operation_type::res_bit, {0xCB, 0xBA}, addressing_mode::bit, addressing_mode::register_d },
	{ operation_type::res_bit, {0xCB, 0x92}, addressing_mode::bit, addressing_mode::register_d },
	{ operation_type::res_bit, {0xCB, 0xB2}, addressing_mode::bit, addressing_mode::register_d },
	{ operation_type::res_bit, {0xCB, 0xA2}, addressing_mode::bit, addressing_mode::register_d },
	{ operation_type::res_bit, {0xCB, 0xAA}, addressing_mode::bit, addressing_mode::register_d },
	{ operation_type::res_bit, {0xCB, 0x82}, addressing_mode::bit, addressing_mode::register_d },
	{ operation_type::res_bit, {0xCB, 0x8A}, addressing_mode::bit, addressing_mode::register_d },
	{ operation_type::res_bit, {0xCB, 0x9A}, addressing_mode::bit, addressing_mode::register_d },
	{ operation_type::res_bit, {0xCB, 0xA3}, addressing_mode::bit, addressing_mode::register_e },
	{ operation_type::res_bit, {0xCB, 0xAB}, addressing_mode::bit, addressing_mode::register_e },
	{ operation_type::res_bit, {0xCB, 0xBB}, addressing_mode::bit, addressing_mode::register_e },
	{ operation_type::res_bit, {0xCB, 0xB3}, addressing_mode::bit, addressing_mode::register_e },
	{ operation_type::res_bit, {0xCB, 0x83}, addressing_mode::bit, addressing_mode::register_e },
	{ operation_type::res_bit, {0xCB, 0x9B}, addressing_mode::bit, addressing_mode::register_e },
	{ operation_type::res_bit, {0xCB, 0x8B}, addressing_mode::bit, addressing_mode::register_e },
	{ operation_type::res_bit, {0xCB, 0x93}, addressing_mode::bit, addressing_mode::register_e },
	{ operation_type::res_bit, {0xCB, 0x9C}, addressing_mode::bit, addressing_mode::register_h },
	{ operation_type::res_bit, {0xCB, 0xBC}, addressing_mode::bit, addressing_mode::register_h },
	{ operation_type::res_bit, {0xCB, 0xA4}, addressing_mode::bit, addressing_mode::register_h },
	{ operation_type::res_bit, {0xCB, 0x84}, addressing_mode::bit, addressing_mode::register_h },
	{ operation_type::res_bit, {0xCB, 0x94}, addressing_mode::bit, addressing_mode::register_h },
	{ operation_type::res_bit, {0xCB, 0xAC}, addressing_mode::bit, addressing_mode::register_h },
	{ operation_type::res_bit, {0xCB, 0xB4}, addressing_mode::bit, addressing_mode::register_h },
	{ operation_type::res_bit, {0xCB, 0x8C}, addressing_mode::bit, addressing_mode::register_h },
	{ operation_type::res_bit, {0xCB, 0x9D}, addressing_mode::bit, addressing_mode::register_l },
	{ operation_type::res_bit, {0xCB, 0xBD}, addressing_mode::bit, addressing_mode::register_l },
	{ operation_type::res_bit, {0xCB, 0x85}, addressing_mode::bit, addressing_mode::register_l },
	{ operation_type::res_bit, {0xCB, 0xB5}, addressing_mode::bit, addressing_mode::register_l },
	{ operation_type::res_bit, {0xCB, 0x8D}, addressing_mode::bit, addressing_mode::register_l },
	{ operation_type::res_bit, {0xCB, 0xAD}, addressing_mode::bit, addressing_mode::register_l },
	{ operation_type::res_bit, {0xCB, 0x95}, addressing_mode::bit, addressing_mode::register_l },
	{ operation_type::res_bit, {0xCB, 0xA5}, addressing_mode::bit, addressing_mode::register_l },
	{ operation_type::res_bit_at, {0xCB, 0xB6}, addressing_mode::bit, addressing_mode::indirect_hl },
	{ operation_type::res_bit_at, {0xCB, 0xAE}, addressing_mode::bit, addressing_mode::indirect_hl },
	{ operation_type::res_bit_at, {0xCB, 0xA6}, addressing_mode::bit, addressing_mode::indirect_hl },
	{ operation_type::res_bit_at, {0xCB, 0x9E}, addressing_mode::bit, addressing_mode::indirect_hl },
	{ operation_type::res_bit_at, {0xCB, 0x96}, addressing_mode::bit, addressing_mode::indirect_hl },
	{ operation_type::res_bit_at, {0xCB, 0x8E}, addressing_mode::bit, addressing_mode::indirect_hl },
	{ operation_type::res_bit_at, {0xCB, 0x86}, addressing_mode::bit, addressing_mode::indirect_hl },
	{ operation_type::res_bit_at, {0xCB, 0xBE}, addressing_mode::bit, addressing_mode::indirect_hl },
	{ operation_type::bit_group, {0xDD, 0xCB}, addressing_mode::immediate_bit, addressing_mode::indexed_ix },
	{ operation_type::bit_group, {0xFD, 0xCB}, addressing_mode::immediate_bit, addressing_mode::indexed_iy },
	{ operation_type::daa, {0x27}, addressing_mode::implied, addressing_mode::implied },
	{ operation_type::cpl, {0x2F}, addressing_mode::implied, addressing_mode::implied },
	{ operation_type::neg, {0xED, 0x44}, addressing_mode::implied, addressing_mode::implied },
	{ operation_type::ccf, {0x3F}, addressing_mode::implied, addressing_mode::implied },
	{ operation_type::scf, {0x37}, addressing_mode::implied, addressing_mode::implied },
	{ operation_type::di, {0xF3}, addressing_mode::none, addressing_mode::none },
	{ operation_type::ei, {0xFB}, addressing_mode::none, addressing_mode::none },
	{ operation_type::nop, {0x00}, addressing_mode::none, addressing_mode::none },
	{ operation_type::halt, {0x76}, addressing_mode::none, addressing_mode::none },
	{ operation_type::im0, {0xED, 0x46}, addressing_mode::none, addressing_mode::none },
	{ operation_type::im1, {0xED, 0x56}, addressing_mode::none, addressing_mode::none },
	{ operation_type::im2, {0xED, 0x5E}, addressing_mode::none, addressing_mode::none },
};


}

#endif // __INSTRUCTIONS_HPP__
