version: '3'

services:
  genesis_clang_dev:
    # use genesis_alpine_clang or genesis_alpine_gcc
    image: genesis_alpine_clang
    working_dir: /genesis
    volumes:
      - ../genesis:/genesis/genesis/:ro
      - ../tests:/genesis/tests:ro
      - ../CMakeLists.txt:/genesis/CMakeLists.txt:ro
    tty: true
