name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dockerfile: [DockerfileAlpineGCC, DockerfileAlpineClang]

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file docker/${{matrix.dockerfile}} --tag genesis

    - name: Build the project
      run: |
        docker run --name genesis_container -t genesis /bin/sh -c make -j 2
        docker commit genesis_container genesis

    - name: Run the tests
      run: docker run -t genesis /bin/sh -c ctest
